console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#1A1826'      # Darker, more intense shade
  blue = '#89B4FA'       # Softer, more pastel blue
  green = '#A6E3A1'      # Muted sage green
  grey = '#9399B2'       # Soft, muted grey with slight blue undertone
  magenta = '#CBA6F7'    # Soft lavender purple
  orange = '#FAB387'     # Soft peach
  red = '#FF6B81'        # More vibrant rose red
  white = '#CDD6F4'      # Softer white with slight blue tint
  yellow = '#F9E2AF'     # Muted warm yellow

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:blue'
    background = 'transparent'
    template = '{{ .Path }}'
    
    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{if or (.Working.Changed) (.Staging.Changed) }}*{{end}} <cyan>{{ if gt .Behind 0 }}⇣{{end}}{{ if gt .Ahead 0 }}⇡{{end}}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  # [[blocks.segments]]
  #   type = 'spotify'
  #   style = 'powerline'
  #   powerline_symbol = '♫'
  #   foreground = 'p:white'
  #   background = 'transparent'

  #   [blocks.segments.properties]
  #     playing_icon = '♫ '
  #     paused_icon = '⏸ '
  #     stopped_icon = '⏹ '

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "p:yellow"
    background = "transparent"
    template = " {{ .FormattedMs }}"

    [blocks.segments.properties]
      threshold = 5000
      style = "austin"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'p:magenta'
  background = 'transparent'
  template = '❯❯ '
